services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Foyer
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app-foyer:
    image: sarra24/foyerproject:latest
    container_name: app-foyer
    depends_on:
      - mysqldb
    ports:
      - "8089:8089"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/Foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root
    - SPRING_JPA_SHOW_SQL=false
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    - SERVER_PORT=8089
    - SERVER_ADDRESS=0.0.0.0
    - SERVER_SERVLET_CONTEXT_PATH=/Foyer
    - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
    - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
    - MANAGEMENT_ENDPOINTS_WEB_BASE_PATH=/actuator
    - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
    - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
    - SPRING_SECURITY_USER_PASSWORD=none

volumes:
  db_data:
