version: "3.8"

services:
  mysqldb:
    image: mysql:8.3.0
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=tpfoyer_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-foyer:
    depends_on:
      - mysqldb
    image: issamguezmir/mon-projet-foyer:latest
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null,
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db: